# Generated by Django 5.1.15 on 2025-12-06 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_lesson_reminders', models.BooleanField(default=True, verbose_name='Przypomnienia o lekcjach (email)')),
                ('email_lesson_changes', models.BooleanField(default=True, verbose_name='Zmiany w lekcjach (email)')),
                ('email_messages', models.BooleanField(default=True, verbose_name='Wiadomości (email)')),
                ('email_invoices', models.BooleanField(default=True, verbose_name='Faktury (email)')),
                ('email_system', models.BooleanField(default=True, verbose_name='Powiadomienia systemowe (email)')),
                ('email_marketing', models.BooleanField(default=False, verbose_name='Informacje marketingowe (email)')),
                ('sms_lesson_reminders', models.BooleanField(default=False, verbose_name='Przypomnienia o lekcjach (SMS)')),
                ('sms_lesson_changes', models.BooleanField(default=True, verbose_name='Zmiany w lekcjach (SMS)')),
                ('sms_urgent', models.BooleanField(default=True, verbose_name='Pilne powiadomienia (SMS)')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='Powiadomienia push włączone')),
                ('push_lesson_reminders', models.BooleanField(default=True, verbose_name='Przypomnienia o lekcjach (push)')),
                ('push_messages', models.BooleanField(default=True, verbose_name='Wiadomości (push)')),
                ('in_app_enabled', models.BooleanField(default=True, verbose_name='Powiadomienia w aplikacji')),
                ('reminder_hours_before', models.PositiveSmallIntegerField(default=24, help_text='Ile godzin przed lekcją wysłać przypomnienie', verbose_name='Godziny przed lekcją (przypomnienie)')),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Nie wysyłaj powiadomień po tej godzinie', null=True, verbose_name='Cisza nocna od')),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='Nie wysyłaj powiadomień przed tą godziną', null=True, verbose_name='Cisza nocna do')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Preferencje powiadomień',
                'verbose_name_plural': 'Preferencje powiadomień',
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='ParentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('view_only', 'Tylko podgląd'), ('limited', 'Ograniczony'), ('full', 'Pełny')], default='view_only', max_length=20, verbose_name='Poziom dostępu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('can_view_lessons', models.BooleanField(default=True, verbose_name='Może przeglądać lekcje')),
                ('can_view_attendance', models.BooleanField(default=True, verbose_name='Może przeglądać obecności')),
                ('can_view_grades', models.BooleanField(default=True, verbose_name='Może przeglądać oceny')),
                ('can_view_invoices', models.BooleanField(default=True, verbose_name='Może przeglądać faktury')),
                ('can_message_tutors', models.BooleanField(default=True, verbose_name='Może pisać do korepetytorów')),
                ('can_cancel_lessons', models.BooleanField(default=False, verbose_name='Może odwoływać lekcje')),
                ('can_reschedule_lessons', models.BooleanField(default=False, verbose_name='Może przełożyć lekcje')),
                ('invited_email', models.EmailField(blank=True, max_length=254, verbose_name='Zaproszony email')),
                ('invitation_token', models.CharField(blank=True, max_length=64, verbose_name='Token zaproszenia')),
                ('invitation_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Zaproszenie wysłane')),
                ('invitation_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Zaproszenie zaakceptowane')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_access_grants', to=settings.AUTH_USER_MODEL, verbose_name='Rodzic')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_access_received', to=settings.AUTH_USER_MODEL, verbose_name='Uczeń')),
            ],
            options={
                'verbose_name': 'Dostęp rodzica',
                'verbose_name_plural': 'Dostępy rodziców',
                'db_table': 'parent_access',
                'indexes': [models.Index(fields=['parent'], name='parent_acce_parent__5b0af2_idx'), models.Index(fields=['student'], name='parent_acce_student_0e62e6_idx'), models.Index(fields=['is_active'], name='parent_acce_is_acti_58a798_idx'), models.Index(fields=['invitation_token'], name='parent_acce_invitat_3dd377_idx')],
                'unique_together': {('parent', 'student')},
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Logowanie'), ('logout', 'Wylogowanie'), ('password_change', 'Zmiana hasła'), ('profile_update', 'Aktualizacja profilu'), ('lesson_view', 'Przeglądanie lekcji'), ('message_send', 'Wysłanie wiadomości'), ('file_download', 'Pobranie pliku'), ('settings_change', 'Zmiana ustawień')], max_length=30, verbose_name='Typ aktywności')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Opis')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadane')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adres IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Aktywność użytkownika',
                'verbose_name_plural': 'Aktywności użytkowników',
                'db_table': 'user_activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='user_activi_user_id_260c6d_idx'), models.Index(fields=['activity_type'], name='user_activi_activit_534635_idx'), models.Index(fields=['created_at'], name='user_activi_created_9fa3ca_idx'), models.Index(fields=['user', 'activity_type'], name='user_activi_user_id_290628_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_user_id', models.IntegerField(verbose_name='Oryginalne ID użytkownika')),
                ('email_hash', models.CharField(help_text='SHA-256 hash of original email for reference', max_length=64, verbose_name='Hash email')),
                ('archived_data', models.JSONField(help_text='Encrypted user data', verbose_name='Zarchiwizowane dane')),
                ('reason', models.CharField(choices=[('user_request', 'Na żądanie użytkownika'), ('admin_action', 'Akcja administratora'), ('inactivity', 'Nieaktywność'), ('gdpr_request', 'Żądanie RODO')], max_length=30, verbose_name='Powód archiwizacji')),
                ('notes', models.TextField(blank=True, verbose_name='Notatki')),
                ('retention_until', models.DateField(help_text='Date until which archive must be retained', verbose_name='Przechowywać do')),
                ('is_anonymized', models.BooleanField(default=False, verbose_name='Zanonimizowane')),
                ('anonymized_at', models.DateTimeField(blank=True, null=True, verbose_name='Data anonimizacji')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_users', to=settings.AUTH_USER_MODEL, verbose_name='Zarchiwizowane przez')),
            ],
            options={
                'verbose_name': 'Archiwum użytkownika',
                'verbose_name_plural': 'Archiwa użytkowników',
                'db_table': 'user_archives',
                'indexes': [models.Index(fields=['original_user_id'], name='user_archiv_origina_090ef5_idx'), models.Index(fields=['email_hash'], name='user_archiv_email_h_9112f2_idx'), models.Index(fields=['retention_until'], name='user_archiv_retenti_5e16b2_idx'), models.Index(fields=['created_at'], name='user_archiv_created_f299af_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('tutor_student', 'Korepetytor-Uczeń'), ('parent_student', 'Rodzic-Uczeń')], max_length=30, verbose_name='Typ relacji')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywna')),
                ('notes', models.TextField(blank=True, verbose_name='Notatki')),
                ('started_at', models.DateField(blank=True, null=True, verbose_name='Data rozpoczęcia')),
                ('ended_at', models.DateField(blank=True, null=True, verbose_name='Data zakończenia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to=settings.AUTH_USER_MODEL, verbose_name='Od użytkownika')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to=settings.AUTH_USER_MODEL, verbose_name='Do użytkownika')),
            ],
            options={
                'verbose_name': 'Relacja użytkowników',
                'verbose_name_plural': 'Relacje użytkowników',
                'db_table': 'user_relationships',
                'indexes': [models.Index(fields=['from_user'], name='user_relati_from_us_5ad889_idx'), models.Index(fields=['to_user'], name='user_relati_to_user_189a76_idx'), models.Index(fields=['relationship_type'], name='user_relati_relatio_8cc7b3_idx'), models.Index(fields=['is_active'], name='user_relati_is_acti_13e1fd_idx')],
                'unique_together': {('from_user', 'to_user', 'relationship_type')},
            },
        ),
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Telefon'), ('identity', 'Tożsamość')], max_length=20, verbose_name='Typ weryfikacji')),
                ('status', models.CharField(choices=[('pending', 'Oczekujące'), ('verified', 'Zweryfikowane'), ('failed', 'Niepowodzenie'), ('expired', 'Wygasłe')], default='pending', max_length=20, verbose_name='Status')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Token')),
                ('value_to_verify', models.CharField(help_text='Email or phone number being verified', max_length=255, verbose_name='Wartość do weryfikacji')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Liczba prób')),
                ('max_attempts', models.PositiveSmallIntegerField(default=3, verbose_name='Maksymalna liczba prób')),
                ('expires_at', models.DateTimeField(verbose_name='Wygasa')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Zweryfikowano')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Weryfikacja użytkownika',
                'verbose_name_plural': 'Weryfikacje użytkowników',
                'db_table': 'user_verifications',
                'indexes': [models.Index(fields=['user'], name='user_verifi_user_id_e6d449_idx'), models.Index(fields=['token'], name='user_verifi_token_294719_idx'), models.Index(fields=['status'], name='user_verifi_status_4ecc5e_idx'), models.Index(fields=['expires_at'], name='user_verifi_expires_212d7b_idx')],
            },
        ),
    ]
