# Generated by Django 5.1.15 on 2025-12-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_notificationpreference_parentaccess_useractivity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('tutor', 'Korepetytor'), ('student', 'Uczeń'), ('parent', 'Rodzic')], default='student', max_length=20, verbose_name='Rola'),
        ),
    ]
