# Generated by Django 5.1.15 on 2025-12-06 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Pytanie')),
                ('answer', models.TextField(verbose_name='Odpowiedź')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='Kategoria')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('is_published', models.BooleanField(default=True, verbose_name='Opublikowane')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'db_table': 'faq_items',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Imię')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('subject', models.CharField(max_length=200, verbose_name='Temat')),
                ('message', models.TextField(verbose_name='Wiadomość')),
                ('status', models.CharField(choices=[('new', 'Nowy'), ('contacted', 'Skontaktowany'), ('converted', 'Skonwertowany'), ('lost', 'Utracony')], default='new', max_length=20, verbose_name='Status')),
                ('gdpr_consent', models.BooleanField(default=False, verbose_name='Zgoda RODO')),
                ('marketing_consent', models.BooleanField(default=False, verbose_name='Zgoda marketingowa')),
                ('source', models.CharField(default='website', max_length=50, verbose_name='Źródło')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leady',
                'db_table': 'leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('page_key', models.CharField(max_length=50, unique=True, verbose_name='Klucz strony')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Podtytuł')),
                ('content', models.TextField(blank=True, verbose_name='Treść')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Dane dodatkowe')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywna')),
            ],
            options={
                'verbose_name': 'Treść strony',
                'verbose_name_plural': 'Treści stron',
                'db_table': 'page_contents',
            },
        ),
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Na Piątkę', max_length=100, verbose_name='Nazwa')),
                ('tagline', models.CharField(blank=True, max_length=200, verbose_name='Slogan')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Adres')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Miasto')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Kod pocztowy')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Szerokość geo')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Długość geo')),
                ('opening_hours', models.JSONField(blank=True, default=dict, verbose_name='Godziny otwarcia')),
                ('social_media', models.JSONField(blank=True, default=dict, verbose_name='Social media')),
            ],
            options={
                'verbose_name': 'Informacje o szkole',
                'verbose_name_plural': 'Informacje o szkole',
                'db_table': 'school_info',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, verbose_name='Imię ucznia')),
                ('parent_name', models.CharField(blank=True, max_length=100, verbose_name='Imię rodzica')),
                ('content', models.TextField(verbose_name='Treść opinii')),
                ('rating', models.PositiveIntegerField(default=5, verbose_name='Ocena')),
                ('subject', models.CharField(blank=True, max_length=50, verbose_name='Przedmiot')),
                ('level', models.CharField(blank=True, max_length=50, verbose_name='Poziom')),
                ('image', models.ImageField(blank=True, upload_to='testimonials/', verbose_name='Zdjęcie')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Zweryfikowana')),
                ('is_published', models.BooleanField(default=False, verbose_name='Opublikowana')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
            ],
            options={
                'verbose_name': 'Opinia',
                'verbose_name_plural': 'Opinie',
                'db_table': 'testimonials',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Imię')),
                ('surname', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Stanowisko')),
                ('bio', models.TextField(blank=True, verbose_name='Opis')),
                ('expertise', models.JSONField(blank=True, default=list, verbose_name='Specjalizacje')),
                ('image', models.ImageField(blank=True, upload_to='team/', verbose_name='Zdjęcie')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('is_published', models.BooleanField(default=True, verbose_name='Opublikowany')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Członek zespołu',
                'verbose_name_plural': 'Członkowie zespołu',
                'db_table': 'team_members',
                'ordering': ['order_index'],
            },
        ),
    ]
