# Generated by Django 5.1.15 on 2025-12-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('icon_svg', models.TextField(blank=True, verbose_name='Ikona SVG')),
                ('color', models.CharField(default='brand', help_text='np. brand, emerald, blue, red', max_length=50, verbose_name='Kolor')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('is_published', models.BooleanField(default=True, verbose_name='Opublikowany')),
            ],
            options={
                'verbose_name': 'Poziom edukacyjny',
                'verbose_name_plural': 'Poziomy edukacyjne',
                'db_table': 'education_levels',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='LandingStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Etykieta')),
                ('value', models.CharField(max_length=50, verbose_name='Wartość')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Opis')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Ikona (SVG lub klasa)')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('is_published', models.BooleanField(default=True, verbose_name='Opublikowane')),
            ],
            options={
                'verbose_name': 'Statystyka',
                'verbose_name_plural': 'Statystyki',
                'db_table': 'landing_statistics',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='LandingSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('short_description', models.TextField(verbose_name='Krótki opis')),
                ('full_description', models.TextField(blank=True, verbose_name='Pełny opis')),
                ('icon_svg', models.TextField(verbose_name='Ikona SVG')),
                ('color_from', models.CharField(default='blue-500', help_text='np. blue-500, emerald-500, amber-500', max_length=50, verbose_name='Kolor gradient (od)')),
                ('color_to', models.CharField(default='indigo-600', help_text='np. indigo-600, teal-600, orange-600', max_length=50, verbose_name='Kolor gradient (do)')),
                ('levels', models.CharField(default='Wszystkie poziomy', help_text='np. "A1 - C2" lub "Wszystkie poziomy"', max_length=100, verbose_name='Poziomy')),
                ('topics', models.JSONField(blank=True, default=list, help_text='Lista tematów do wyświetlenia w modalu', verbose_name='Tematy')),
                ('target_groups', models.JSONField(blank=True, default=list, help_text='Lista grup docelowych', verbose_name='Grupy docelowe')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('is_published', models.BooleanField(default=True, verbose_name='Opublikowany')),
                ('is_featured', models.BooleanField(default=False, help_text='Wyróżnione przedmioty zajmują więcej miejsca', verbose_name='Wyróżniony')),
            ],
            options={
                'verbose_name': 'Przedmiot (landing)',
                'verbose_name_plural': 'Przedmioty (landing)',
                'db_table': 'landing_subjects',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='LessonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Podtytuł')),
                ('description', models.TextField(verbose_name='Opis')),
                ('icon_svg', models.TextField(verbose_name='Ikona SVG')),
                ('color', models.CharField(default='brand', max_length=50, verbose_name='Kolor')),
                ('features', models.JSONField(default=list, help_text='Lista cech/zalet tej formy zajęć', verbose_name='Cechy')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('is_published', models.BooleanField(default=True, verbose_name='Opublikowany')),
            ],
            options={
                'verbose_name': 'Forma zajęć',
                'verbose_name_plural': 'Formy zajęć',
                'db_table': 'lesson_types',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='PricingPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('sessions_count', models.PositiveIntegerField(verbose_name='Liczba spotkań')),
                ('individual_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena indywidualna (od)')),
                ('group_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena grupowa (od)')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Najpopularniejszy')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('is_published', models.BooleanField(default=True, verbose_name='Opublikowany')),
            ],
            options={
                'verbose_name': 'Pakiet cenowy',
                'verbose_name_plural': 'Pakiety cenowe',
                'db_table': 'pricing_packages',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='WhyUsCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tytuł')),
                ('description', models.TextField(verbose_name='Opis')),
                ('icon', models.TextField(blank=True, verbose_name='Ikona SVG')),
                ('color', models.CharField(default='brand', help_text='Nazwa koloru: brand, emerald, blue, purple, orange, teal', max_length=50, verbose_name='Kolor')),
                ('link', models.CharField(blank=True, max_length=200, verbose_name='Link (opcjonalnie)')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('is_published', models.BooleanField(default=True, verbose_name='Opublikowane')),
            ],
            options={
                'verbose_name': 'Karta "Dlaczego my"',
                'verbose_name_plural': 'Karty "Dlaczego my"',
                'db_table': 'why_us_cards',
                'ordering': ['order_index'],
            },
        ),
    ]
