# Generated by Django 5.1.15 on 2025-12-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_educationlevel_landingstatistic_landingsubject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinfo',
            name='copyright_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tekst copyright'),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='favicon',
            field=models.ImageField(blank=True, upload_to='school/', verbose_name='Favicon'),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='footer_text',
            field=models.TextField(blank=True, verbose_name='Tekst stopki'),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='logo',
            field=models.ImageField(blank=True, upload_to='school/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='logo_dark',
            field=models.ImageField(blank=True, upload_to='school/', verbose_name='Logo (ciemne tło)'),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='phone_secondary',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefon dodatkowy'),
        ),
    ]
