# Generated by Django 5.1.4 on 2025-12-06 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(blank=True, help_text='np. 7A, 3LO', max_length=10, verbose_name='Klasa')),
                ('current_level', models.CharField(blank=True, max_length=50, verbose_name='Aktualny poziom')),
                ('learning_goals', models.TextField(blank=True, verbose_name='Cele nauki')),
                ('parent_name', models.CharField(blank=True, max_length=100, verbose_name='Imię rodzica')),
                ('parent_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon rodzica')),
                ('parent_email', models.EmailField(blank=True, max_length=254, verbose_name='Email rodzica')),
                ('secondary_parent_name', models.CharField(blank=True, max_length=100, verbose_name='Imię drugiego rodzica')),
                ('secondary_parent_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon drugiego rodzica')),
                ('emergency_contact', models.CharField(blank=True, max_length=100, verbose_name='Kontakt awaryjny')),
                ('notes', models.TextField(blank=True, verbose_name='Notatki')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Data dołączenia')),
                ('total_lessons', models.PositiveIntegerField(default=0, verbose_name='Wszystkie lekcje')),
                ('completed_lessons', models.PositiveIntegerField(default=0, verbose_name='Ukończone lekcje')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Profil ucznia',
                'verbose_name_plural': 'Profile uczniów',
                'db_table': 'student_profiles',
            },
        ),
    ]
