# Generated by Django 5.1.15 on 2025-12-08 14:27

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Numer faktury')),
                ('month_year', models.CharField(max_length=7, verbose_name='Miesiąc')),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Kwota netto')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Kwota VAT')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Kwota brutto')),
                ('status', models.CharField(choices=[('GENERATED', 'Wygenerowana'), ('SENT', 'Wysłana'), ('PAID', 'Opłacona'), ('OVERDUE', 'Zaległa'), ('CANCELLED', 'Anulowana'), ('CORRECTED', 'Skorygowana')], default='GENERATED', max_length=20, verbose_name='Status')),
                ('issue_date', models.DateField(verbose_name='Data wystawienia')),
                ('due_date', models.DateField(verbose_name='Termin płatności')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Data płatności')),
                ('pdf_path', models.CharField(blank=True, max_length=255, verbose_name='Ścieżka PDF')),
                ('notes', models.TextField(blank=True, verbose_name='Notatki')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to=settings.AUTH_USER_MODEL, verbose_name='Uczeń')),
            ],
            options={
                'verbose_name': 'Faktura',
                'verbose_name_plural': 'Faktury',
                'db_table': 'invoices',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500, verbose_name='Opis')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ilość')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena jednostkowa')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Wartość')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice', verbose_name='Faktura')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='lessons.lesson', verbose_name='Lekcja')),
            ],
            options={
                'verbose_name': 'Pozycja faktury',
                'verbose_name_plural': 'Pozycje faktur',
                'db_table': 'invoice_items',
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['student'], name='invoices_student_a32263_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['month_year'], name='invoices_month_y_94663a_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='invoices_status_07776b_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['issue_date'], name='invoices_issue_d_6fe766_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='invoices_due_dat_039a25_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['invoice'], name='invoice_ite_invoice_ab1faa_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['lesson'], name='invoice_ite_lesson__8b3b07_idx'),
        ),
    ]
