# Generated by Django 5.1.4 on 2025-12-06 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Utworzenie'), ('update', 'Aktualizacja'), ('delete', 'Usunięcie')], max_length=20, verbose_name='Akcja')),
                ('model_type', models.CharField(max_length=100, verbose_name='Typ modelu')),
                ('model_id', models.CharField(blank=True, max_length=100, verbose_name='ID rekordu')),
                ('old_values', models.JSONField(blank=True, null=True, verbose_name='Poprzednie wartości')),
                ('new_values', models.JSONField(blank=True, null=True, verbose_name='Nowe wartości')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adres IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log audytu',
                'verbose_name_plural': 'Logi audytu',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='audit_logs_user_id_73c422_idx'), models.Index(fields=['model_type'], name='audit_logs_model_t_fc65f6_idx'), models.Index(fields=['created_at'], name='audit_logs_created_262184_idx'), models.Index(fields=['action'], name='audit_logs_action_31f574_idx')],
            },
        ),
    ]
