# Generated by Django 5.1.15 on 2025-12-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Utworzenie'), ('update', 'Aktualizacja'), ('delete', 'Usunięcie'), ('export', 'Eksport'), ('bulk_update', 'Aktualizacja zbiorcza'), ('login', 'Logowanie'), ('logout', 'Wylogowanie')], max_length=20, verbose_name='Akcja'),
        ),
    ]
