# Generated by Django 5.1.4 on 2025-12-06 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Temat')),
                ('content', models.TextField(verbose_name='Treść')),
                ('is_read', models.BooleanField(default=False, verbose_name='Przeczytana')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Data przeczytania')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='Załączniki')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='internal_messages.message')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Odbiorca')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Nadawca')),
            ],
            options={
                'verbose_name': 'Wiadomość',
                'verbose_name_plural': 'Wiadomości',
                'db_table': 'messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender'], name='messages_sender__6ae55a_idx'), models.Index(fields=['recipient'], name='messages_recipie_ef005d_idx'), models.Index(fields=['is_read'], name='messages_is_read_6a69c0_idx'), models.Index(fields=['created_at'], name='messages_created_919c58_idx')],
            },
        ),
    ]
