# Generated by Django 5.1.15 on 2025-12-08 17:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Temat')),
                ('is_group_chat', models.BooleanField(default=False, verbose_name='Czat grupowy')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('last_message_at', models.DateTimeField(auto_now_add=True, verbose_name='Ostatnia wiadomość')),
            ],
            options={
                'verbose_name': 'Konwersacja',
                'verbose_name_plural': 'Konwersacje',
                'db_table': 'conversations',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='Treść')),
                ('content_type', models.CharField(choices=[('TEXT', 'Tekst'), ('RICH_TEXT', 'Tekst sformatowany'), ('CODE', 'Kod'), ('SYSTEM', 'Systemowa')], default='TEXT', max_length=20, verbose_name='Typ treści')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Edytowana')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='Data edycji')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Usunięta')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Data usunięcia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='internal_messages.conversation', verbose_name='Konwersacja')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='internal_messages.message', verbose_name='Odpowiedź na')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Nadawca')),
            ],
            options={
                'verbose_name': 'Wiadomość',
                'verbose_name_plural': 'Wiadomości',
                'db_table': 'messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255, verbose_name='Nazwa pliku')),
                ('file', models.FileField(upload_to='message_attachments/%Y/%m/', verbose_name='Plik')),
                ('file_size', models.PositiveIntegerField(verbose_name='Rozmiar (bytes)')),
                ('mime_type', models.CharField(max_length=100, verbose_name='Typ MIME')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Przesłano')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='internal_messages.message', verbose_name='Wiadomość')),
            ],
            options={
                'verbose_name': 'Załącznik',
                'verbose_name_plural': 'Załączniki',
                'db_table': 'message_attachments',
            },
        ),
        migrations.CreateModel(
            name='MessageReadReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='Przeczytano')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='internal_messages.message', verbose_name='Wiadomość')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_read_receipts', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Potwierdzenie odczytu',
                'verbose_name_plural': 'Potwierdzenia odczytu',
                'db_table': 'message_read_receipts',
            },
        ),
        migrations.CreateModel(
            name='ConversationParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Dołączono')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='Opuszczono')),
                ('last_read_at', models.DateTimeField(blank=True, null=True, verbose_name='Ostatnio przeczytano')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Zarchiwizowana')),
                ('is_muted', models.BooleanField(default=False, verbose_name='Wyciszona')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='internal_messages.conversation', verbose_name='Konwersacja')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_participations', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Uczestnik konwersacji',
                'verbose_name_plural': 'Uczestnicy konwersacji',
                'db_table': 'conversation_participants',
                'indexes': [models.Index(fields=['user', 'conversation'], name='conversatio_user_id_bb37a4_idx'), models.Index(fields=['last_read_at'], name='conversatio_last_re_421e10_idx')],
                'unique_together': {('conversation', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', '-created_at'], name='messages_convers_38b855_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender'], name='messages_sender__6ae55a_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereadreceipt',
            index=models.Index(fields=['user'], name='message_rea_user_id_f184be_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagereadreceipt',
            unique_together={('message', 'user')},
        ),
    ]
