# Generated by Django 5.1.15 on 2025-12-08 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Powod')),
                ('status', models.CharField(choices=[('pending', 'Oczekujaca'), ('approved', 'Zaakceptowana'), ('rejected', 'Odrzucona')], default='pending', max_length=20, verbose_name='Status')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='Data zgloszenia')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data rozpatrzenia')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notatka administratora')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_requests', to='lessons.lesson', verbose_name='Lekcja')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_cancellations', to=settings.AUTH_USER_MODEL, verbose_name='Rozpatrzone przez')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_requests', to=settings.AUTH_USER_MODEL, verbose_name='Uczen')),
            ],
            options={
                'verbose_name': 'Prosba o anulowanie',
                'verbose_name_plural': 'Prosby o anulowanie',
                'db_table': 'cancellation_requests',
                'ordering': ['-request_date'],
                'indexes': [models.Index(fields=['status'], name='cancellatio_status_bdd61e_idx'), models.Index(fields=['student'], name='cancellatio_student_a9d6fe_idx'), models.Index(fields=['lesson'], name='cancellatio_lesson__cef537_idx'), models.Index(fields=['request_date'], name='cancellatio_request_fb071e_idx')],
            },
        ),
        migrations.CreateModel(
            name='MakeupLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Oczekujaca'), ('scheduled', 'Zaplanowana'), ('completed', 'Ukonczona'), ('expired', 'Wygasla')], default='pending', max_length=20, verbose_name='Status')),
                ('expires_at', models.DateTimeField(verbose_name='Data wygasniecia')),
                ('notes', models.TextField(blank=True, verbose_name='Notatki')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('new_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='makeup_new', to='lessons.lesson', verbose_name='Nowa lekcja')),
                ('original_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='makeup_original', to='lessons.lesson', verbose_name='Oryginalna lekcja')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='makeup_lessons', to=settings.AUTH_USER_MODEL, verbose_name='Uczen')),
            ],
            options={
                'verbose_name': 'Zajecia zastepcze',
                'verbose_name_plural': 'Zajecia zastepcze',
                'db_table': 'makeup_lessons',
                'ordering': ['expires_at'],
                'indexes': [models.Index(fields=['status'], name='makeup_less_status_d35fd1_idx'), models.Index(fields=['student'], name='makeup_less_student_7e80b7_idx'), models.Index(fields=['expires_at'], name='makeup_less_expires_ffb27b_idx')],
            },
        ),
    ]
