# Generated by Django 5.1.4 on 2025-12-06 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='Opis')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Stawka godzinowa')),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True, verbose_name='Lata doświadczenia')),
                ('education', models.TextField(blank=True, verbose_name='Wykształcenie')),
                ('certifications', models.JSONField(blank=True, default=list, verbose_name='Certyfikaty')),
                ('availability_hours', models.JSONField(blank=True, default=dict, help_text='Weekly availability schedule as JSON', verbose_name='Godziny dostępności')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Zweryfikowany')),
                ('verification_date', models.DateTimeField(blank=True, null=True, verbose_name='Data weryfikacji')),
                ('rating_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Średnia ocena')),
                ('lessons_completed', models.PositiveIntegerField(default=0, verbose_name='Ukończone lekcje')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Profil korepetytora',
                'verbose_name_plural': 'Profile korepetytorów',
                'db_table': 'tutor_profiles',
            },
        ),
        migrations.CreateModel(
            name='TutorSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Stawka za godzinę')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_assignments', to='subjects.level')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_assignments', to='subjects.subject')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_subjects', to='tutors.tutorprofile')),
            ],
            options={
                'verbose_name': 'Przedmiot korepetytora',
                'verbose_name_plural': 'Przedmioty korepetytorów',
                'db_table': 'tutor_subjects',
                'unique_together': {('tutor', 'subject', 'level')},
            },
        ),
    ]
