# Generated by Django 5.1.4 on 2025-12-06 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Ikona')),
                ('color', models.CharField(blank=True, max_length=7, verbose_name='Kolor')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
            ],
            options={
                'verbose_name': 'Przedmiot',
                'verbose_name_plural': 'Przedmioty',
                'db_table': 'subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('color', models.CharField(blank=True, max_length=7, verbose_name='Kolor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
            ],
            options={
                'verbose_name': 'Poziom',
                'verbose_name_plural': 'Poziomy',
                'db_table': 'levels',
                'ordering': ['order_index'],
                'indexes': [models.Index(fields=['order_index'], name='levels_order_i_64d886_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubjectLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_levels', to='subjects.level')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_levels', to='subjects.subject')),
            ],
            options={
                'verbose_name': 'Przedmiot-Poziom',
                'verbose_name_plural': 'Przedmioty-Poziomy',
                'db_table': 'subject_levels',
                'unique_together': {('subject', 'level')},
            },
        ),
    ]
