# Generated by Django 5.1.15 on 2025-12-07 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('attendance_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Frekwencja')),
                ('threshold', models.PositiveIntegerField(default=80, verbose_name='Próg')),
                ('alert_type', models.CharField(default='LOW_ATTENDANCE', max_length=50, verbose_name='Typ alertu')),
                ('status', models.CharField(choices=[('PENDING', 'Oczekujący'), ('RESOLVED', 'Rozwiązany'), ('DISMISSED', 'Odrzucony')], default='PENDING', max_length=20, verbose_name='Status')),
                ('resolution', models.TextField(blank=True, verbose_name='Rozwiązanie')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Data rozwiązania')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Uczeń')),
            ],
            options={
                'verbose_name': 'Alert obecności',
                'verbose_name_plural': 'Alerty obecności',
                'db_table': 'attendance_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('month', models.DateField(verbose_name='Miesiąc')),
                ('attendance_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Frekwencja')),
                ('total_lessons', models.PositiveIntegerField(verbose_name='Łączna liczba lekcji')),
                ('present_count', models.PositiveIntegerField(verbose_name='Obecny')),
                ('absent_count', models.PositiveIntegerField(verbose_name='Nieobecny')),
                ('late_count', models.PositiveIntegerField(verbose_name='Spóźniony')),
                ('excused_count', models.PositiveIntegerField(verbose_name='Usprawiedliwiony')),
                ('pdf_path', models.CharField(blank=True, max_length=255, verbose_name='Ścieżka PDF')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_reports', to=settings.AUTH_USER_MODEL, verbose_name='Uczeń')),
            ],
            options={
                'verbose_name': 'Raport obecności',
                'verbose_name_plural': 'Raporty obecności',
                'db_table': 'attendance_reports',
                'ordering': ['-month'],
                'unique_together': {('student', 'month')},
            },
        ),
    ]
