# Generated by Django 5.1.4 on 2025-12-06 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('start_time', models.DateTimeField(verbose_name='Czas rozpoczęcia')),
                ('end_time', models.DateTimeField(verbose_name='Czas zakończenia')),
                ('is_group_lesson', models.BooleanField(default=False, verbose_name='Lekcja grupowa')),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True, verbose_name='Maksymalna liczba uczestników')),
                ('status', models.CharField(choices=[('scheduled', 'Zaplanowana'), ('ongoing', 'W trakcie'), ('completed', 'Ukończona'), ('cancelled', 'Anulowana')], default='scheduled', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notatki')),
                ('color', models.CharField(blank=True, help_text='Hex color for calendar display', max_length=7, verbose_name='Kolor')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Cykliczna')),
                ('recurrence_rule', models.JSONField(blank=True, null=True, verbose_name='Reguła powtarzania')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='subjects.level', verbose_name='Poziom')),
                ('parent_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='lessons.lesson')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='rooms.room', verbose_name='Sala')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='subjects.subject', verbose_name='Przedmiot')),
                ('tutor', models.ForeignKey(limit_choices_to={'role': 'tutor'}, on_delete=django.db.models.deletion.PROTECT, related_name='tutor_lessons', to=settings.AUTH_USER_MODEL, verbose_name='Korepetytor')),
            ],
            options={
                'verbose_name': 'Lekcja',
                'verbose_name_plural': 'Lekcje',
                'db_table': 'lessons',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='LessonStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_status', models.CharField(choices=[('unknown', 'Nieznany'), ('present', 'Obecny'), ('absent', 'Nieobecny'), ('late', 'Spóźniony'), ('excused', 'Usprawiedliwiony')], default='unknown', max_length=20, verbose_name='Status obecności')),
                ('attendance_marked_at', models.DateTimeField(blank=True, null=True, verbose_name='Czas oznaczenia')),
                ('notes', models.TextField(blank=True, verbose_name='Notatki')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('attendance_marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_students', to='lessons.lesson')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_lessons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uczeń na lekcji',
                'verbose_name_plural': 'Uczniowie na lekcjach',
                'db_table': 'lesson_students',
            },
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['start_time'], name='lessons_start_t_294a6a_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['end_time'], name='lessons_end_tim_810eaa_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['tutor'], name='lessons_tutor_i_4f08b8_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['room'], name='lessons_room_id_8daf2d_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['status'], name='lessons_status_616d5a_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['start_time', 'end_time'], name='lessons_start_t_f960c9_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonstudent',
            index=models.Index(fields=['lesson'], name='lesson_stud_lesson__233430_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonstudent',
            index=models.Index(fields=['student'], name='lesson_stud_student_17a6d1_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonstudent',
            index=models.Index(fields=['attendance_status'], name='lesson_stud_attenda_52022e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonstudent',
            unique_together={('lesson', 'student')},
        ),
    ]
