# Generated by Django 5.1.15 on 2025-12-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonstudent',
            name='attendance_notes',
            field=models.TextField(blank=True, verbose_name='Notatki obecności'),
        ),
        migrations.AddField(
            model_name='lessonstudent',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Czas wejścia'),
        ),
        migrations.AddField(
            model_name='lessonstudent',
            name='check_out_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Czas wyjścia'),
        ),
        migrations.AlterField(
            model_name='lessonstudent',
            name='attendance_status',
            field=models.CharField(choices=[('PENDING', 'Oczekujące'), ('PRESENT', 'Obecny'), ('ABSENT', 'Nieobecny'), ('LATE', 'Spóźniony'), ('EXCUSED', 'Usprawiedliwiony')], default='PENDING', max_length=20, verbose_name='Status obecności'),
        ),
    ]
