# Generated by Django 5.1.4 on 2025-12-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa')),
                ('capacity', models.PositiveIntegerField(verbose_name='Pojemność')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Lokalizacja')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('equipment', models.JSONField(blank=True, default=dict, help_text='Equipment as JSON object', verbose_name='Wyposażenie')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywna')),
                ('is_virtual', models.BooleanField(default=False, verbose_name='Wirtualna')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Sale',
                'db_table': 'rooms',
                'ordering': ['name'],
            },
        ),
    ]
