# Generated by Django 5.1.15 on 2025-12-08 17:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('content', models.TextField(verbose_name='Treść')),
                ('type', models.CharField(choices=[('INFO', 'Informacja'), ('WARNING', 'Ostrzeżenie'), ('SUCCESS', 'Sukces'), ('ERROR', 'Błąd')], default='INFO', max_length=20, verbose_name='Typ')),
                ('target_roles', models.JSONField(default=list, help_text='Lista ról, dla których jest widoczne', verbose_name='Role docelowe')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Przypięte')),
                ('publish_at', models.DateTimeField(auto_now_add=True, verbose_name='Data publikacji')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Data wygaśnięcia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ogłoszenie',
                'verbose_name_plural': 'Ogłoszenia',
                'db_table': 'announcements',
                'ordering': ['-is_pinned', '-publish_at'],
                'indexes': [models.Index(fields=['publish_at', 'expires_at'], name='announcemen_publish_106fcd_idx'), models.Index(fields=['is_pinned'], name='announcemen_is_pinn_52ad7c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('message', models.TextField(verbose_name='Treść')),
                ('type', models.CharField(choices=[('SYSTEM', 'Systemowe'), ('MESSAGE', 'Wiadomość'), ('EVENT', 'Wydarzenie'), ('ATTENDANCE', 'Obecność'), ('CANCELLATION', 'Anulowanie'), ('INVOICE', 'Faktura'), ('ANNOUNCEMENT', 'Ogłoszenie'), ('REMINDER', 'Przypomnienie')], default='SYSTEM', max_length=20, verbose_name='Typ')),
                ('priority', models.CharField(choices=[('LOW', 'Niski'), ('NORMAL', 'Normalny'), ('HIGH', 'Wysoki'), ('URGENT', 'Pilny')], default='NORMAL', max_length=20, verbose_name='Priorytet')),
                ('action_url', models.CharField(blank=True, max_length=500, verbose_name='URL akcji')),
                ('action_label', models.CharField(blank=True, max_length=50, verbose_name='Etykieta akcji')),
                ('related_entity_type', models.CharField(blank=True, max_length=50, verbose_name='Typ powiązanego obiektu')),
                ('related_entity_id', models.CharField(blank=True, max_length=50, verbose_name='ID powiązanego obiektu')),
                ('is_read', models.BooleanField(default=False, verbose_name='Przeczytane')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Przeczytano')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Zarchiwizowane')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Zarchiwizowano')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Wygasa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Powiadomienie',
                'verbose_name_plural': 'Powiadomienia',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_c4e471_idx'), models.Index(fields=['expires_at'], name='notificatio_expires_66996e_idx'), models.Index(fields=['type', 'priority'], name='notificatio_type_7e50f5_idx')],
            },
        ),
    ]
