# Generated by Django 5.1.4 on 2025-12-06 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('lesson_reminder', 'Przypomnienie o lekcji'), ('lesson_cancelled', 'Lekcja anulowana'), ('lesson_rescheduled', 'Lekcja przełożona'), ('new_message', 'Nowa wiadomość'), ('invoice_generated', 'Faktura wygenerowana'), ('attendance_marked', 'Obecność oznaczona'), ('system', 'Systemowe')], max_length=30, verbose_name='Typ')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('message', models.TextField(verbose_name='Treść')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Dane dodatkowe')),
                ('is_read', models.BooleanField(default=False, verbose_name='Przeczytane')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Data przeczytania')),
                ('action_url', models.CharField(blank=True, max_length=500, verbose_name='URL akcji')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Powiadomienie',
                'verbose_name_plural': 'Powiadomienia',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='notificatio_user_id_e78525_idx'), models.Index(fields=['is_read'], name='notificatio_is_read_3f8c44_idx'), models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx'), models.Index(fields=['type'], name='notificatio_type_8a8a78_idx')],
            },
        ),
    ]
